<?php
declare(strict_types=1);

/**
 * DB settings priority:
 * 1) config.local.php (generated by install.php)
 * 2) Environment variables
 * 3) Built-in defaults
 */
$localConfig = [];
$localConfigFile = __DIR__.'/config.local.php';
if (is_file($localConfigFile)) {
  $cfg = require $localConfigFile;
  if (is_array($cfg)) $localConfig = $cfg;
}

$DB_HOST = (string)($localConfig['db_host'] ?? getenv('METACAT_DB_HOST') ?: 'localhost');
$DB_NAME = (string)($localConfig['db_name'] ?? getenv('METACAT_DB_NAME') ?: 'metacat');
$DB_USER = (string)($localConfig['db_user'] ?? getenv('METACAT_DB_USER') ?: 'metacat');
$DB_PASS = (string)($localConfig['db_pass'] ?? getenv('METACAT_DB_PASS') ?: 'CHANGE_ME_STRONG');

try {
  $pdo = new PDO(
    "mysql:host=$DB_HOST;dbname=$DB_NAME;charset=utf8mb4",
    $DB_USER,
    $DB_PASS,
    [
      PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
      PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    ]
  );
} catch (PDOException $e) {
  http_response_code(500);
  exit('Erreur de connexion à la base de données.');
}
